sudo: required
services:
  - docker

env:
  global:
    DOCKER_COMPOSE_VERSION: 1.18.0

 before_install:
    - gem update --system
    - gem install bundler
    - gem install fluentd
    - gem install sqlite3

install: true
