language: ruby
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3
  - gem update --system
  - gem install bundler
  - gem install fluentd
  - gem install sqlite3
  - sqlite3 test/test_port_to_service.db < test/test_port_to_service.sql
